def manual():
    filename = "DRAMA T-Tabellen MANUAL"
    outfile = open('%s.txt' % filename, 'w+')
    print("*********************************", file=outfile)
    print("Welcome to DRAMA Stapel Tekenaar!", file=outfile)
    print("*********************************", file=outfile)
    print("by Mathijs Hubrechtsen", file=outfile)
    print("", file=outfile)
    print("1. Introduction:", file=outfile)
    print("What is the DRAMA Stapel Tekenaar? Well, it is what it's name implies, it draws", end=" ", file=outfile)
    print("stapels for the DRAMA simulator used in socs.", file=outfile)
    print("I made this program so I could hone my skils in python/practice socs a bit,", end=" ", file=outfile)
    print("and I thought that maybe some people would like a program like this.", file=outfile)
    print("How does it work you ask? Well first off the user enters a few correct Toekeningstabellen.", file=outfile)
    print("After the user has done this, they simply ask the program to model what the stapel should look like.", file=outfile)
    print("It offers all the basic features you would expect: modifying T-Tabellen, visualizing T-Tabellen, etc.", file=outfile)
    print("The program isn't that complex ~900 lines of code, but it does offer quite a few nifty features.", file=outfile)
    print("Seeing as you're reading this manual right now, you're probably in possession of the program,", end=" ", file=outfile)
    print("so why not try it out! ;-)", file=outfile)
    print("Anyways, thank you for using my program and I hope it will be of some use to you!", file=outfile)
    print("", file=outfile)
    print("2. MANUAL:", file=outfile)
    print("Currently the DRAMA Stapel Tekenaar does not have a GUI, instead it uses", end=" ", file=outfile)
    print("a Terminal-esque UI where the user enters commands in", end=" ", file=outfile)
    print("the terminal/input box of Pycharm.", file=outfile)
    print("When the user starts the program he/she will be asked to press enter.", file=outfile)
    print("The user can also enter MANUAL to download the MANUAL you are now reading.", file=outfile)
    print("After pressing enter, they will be asked to enter a Function name.", file=outfile)
    print("This is the name of the first function you want to create a toekeningstabel of.", file=outfile)
    print("     The Input should be a string (bvb.: HelloWorld)", file=outfile)
    print("After entering a name, the user will be prompted to enter PAR or VAR or RES.", file=outfile)
    print("These commands stand for PARameter, VARiable or RESultaat", end=" ", file=outfile)
    print("the user should enter what kind of toekeningstabel he/she wants to make.", file=outfile)
    print("     The Input should be PAR or VAR or RES (bvb. : PAR)", file=outfile)
    print("After entering both the title of the function and what kind of tabel the user wants,", end=" ", file=outfile)
    print("the user will need to enter the amount of elements used in the tabel", file=outfile)
    print("     The Input should be an integer number (bvb.: 3)", file=outfile)
    print("After entering all of this information, the user will enter the ui.", file=outfile)
    print("Here they can type HELP or DETAILS for more help on what they can do next", file=outfile)
    print("", file=outfile)
    print("3. Extra Information:", file=outfile)
    print("If you are still running into trouble , want to report a bug, or want to help", end=" ", file=outfile)
    print("me improve the DRAMA Stapel Tekenaar, ", end=" ", file=outfile)
    print("do not hesitate to contact me at mathijs.hubrechtsen@student.kuleuven.be!", file=outfile)
    print("Finally I would like to thank you again for using my program,", end=" ", file=outfile)
    print("I'm only still learning so please do give me constructive criticism if it could help me!", file=outfile)
    print("     -Mathijs Hubrechtsen", file=outfile)
    print("", file=outfile)
    print("4. Credits:", file=outfile)
    print("", file=outfile)
    print("*********************************", file=outfile)
    outfile.close()
